// <auto-generated />
using DiningOrderingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiningOrderingSystem.Migrations.NoticeDb
{
    [DbContext(typeof(NoticeDbContext))]
    [Migration("20221111140022_NoticeMigration")]
    partial class NoticeMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("DiningOrderingSystem.Models.Data.NoticeItem", b =>
                {
                    b.Property<string>("NoticeTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoticeContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NoticeTitle");

                    b.ToTable("NoticeItemList");
                });
#pragma warning restore 612, 618
        }
    }
}
