// <auto-generated />
using DiningOrderingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiningOrderingSystem.Migrations.FoodItemDb
{
    [DbContext(typeof(FoodItemDbContext))]
    [Migration("20221110065548_FoodItemMigration")]
    partial class FoodItemMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("DiningOrderingSystem.Models.Data.FoodItem", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Calorie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("FoodItemList");
                });
#pragma warning restore 612, 618
        }
    }
}
